// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vorgzouywgpmrlxrmfir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvcmd6b3V5d2dwbXJseHJtZmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjUwMDgsImV4cCI6MjA2OTg0MTAwOH0.4l_vitAYjnx6QLFImSTfNv7hmR8FUh8mV0YQzth-ci8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});